ingress:
  enabled: true # changed 
  className: "nginx" # changed
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "" # changed
      paths:
        - path: /
          pathType: ImplementationSpecific